// <auto-generated />
namespace LFC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CopilotAddAirplane : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CopilotAddAirplane));
        
        string IMigrationMetadata.Id
        {
            get { return "201511142250314_Copilot-Add-Airplane"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
