// <auto-generated />
namespace LFC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class ComputeCurrentTach : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ComputeCurrentTach));
        
        string IMigrationMetadata.Id
        {
            get { return "201501080654163_Compute-Current-Tach"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
